### ISSUE TITLE
OnEndFunction called on declaration

### ISSUE THREAD

**Issue by Directinvent** [ejulianova/guides#1]
Hi, I've installed guides.js on my webpage https://24onoff.no/interaktiv-demo/ and it's working really well. However, I have one issue. I'm trying to trigger an event when the first demo ends with the .guides({end: }), but for some reason the event is triggered on declaration instead of when the guide ends.

I'm trying to set it up this way:

```javascript
$(document).ready(function(){
      startGuide = $.guides({
         guides: [{
               html: 'Velkommen til en interaktiv demo av 24onoff. <br>Klikk for å starte!'
            }, {
                  element: $('.system-menu'),
                  html: 'Dette er navigasjonsmenyen som tar deg rundt i systemet. <br><span class="guide-next">Neste</span>',
                  color: '#fff'
            }, {
                  element: $('#log-hour'),
                  html: 'Du trykker på denne knappen for å føre timer. <br><br> La oss ta en titt på hvordan det gjøres.',
            }, {
                  end: onEndFunction()
            }]
      });
});
```

Is this an error on my end regarding implementation, or is this an error with the plugin?

**Comment by ejulianova** [comment]
Hi @Directinvent,

Thanks contacting me :-) Can you try to move `end` outside of the `guides` list:
```
$(document).ready(function(){
      startGuide = $.guides({
         guides: [{
               html: 'Velkommen til en interaktiv demo av 24onoff. <br>Klikk for å starte!'
            }, {
                  element: $('.system-menu'),
                  html: 'Dette er navigasjonsmenyen som tar deg rundt i systemet. <br><span class="guide-next">Neste</span>',
                  color: '#fff'
            }, {
                  element: $('#log-hour'),
                  html: 'Du trykker på denne knappen for å føre timer. <br><br> La oss ta en titt på hvordan det gjøres.',
            }],
         end: onEndFunction()
      });
});
```

**Comment by Directinvent** [comment]
Unfortunately it didn't work. Still firing before the guide starts.

**Comment by ejulianova** [comment]
Hey, sorry to hear it's still not working. I've tried that in a codepen: https://codepen.io/anon/pen/GXBmrY and it looks like the "end" callback is executed in when the tour is finished (as expected). Is this what you are trying to do?

**Comment by svennprivate** [comment]
That is so weird. Tried with the codepen you set up and it works! Thanks so much!
